[project]
name = "library"
version = "0.1.0"
description = "Share code for producer, batch and streaming processing."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.25",
    "fsspec>=2026.1.0",
    "polars>=0.19.0",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.5.1",
    "requests>=2.32.5",
    "s3fs>=0.4.2",
    "sqlalchemy>=2.0.45",
]


[build-system]
requires = ["uv_build>=0.9.23,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["core", "infrastructure"]